- Gemfile.lock
PR to update New Relic.  This was pushed to master in error and reverted.
@jimabramson @feanil
> updating nr dependencies

- Gemfile.lock
@e0d @maxrothman 
FYI: @cahrens @gwprice
> Update the version of RPM to the latest released version.

- api/commentables.rb
- spec/api/commentable_spec.rb
> Use thread presenter in thread creation response

- models/comment.rb
- spec/api/comment_spec.rb
> Return comment parent_id field

- api/users.rb
- models/comment.rb
- models/comment_thread.rb
- models/user.rb
- spec/api/user_spec.rb
- spec/models/comment_spec.rb
- spec/models/comment_thread_spec.rb
- spec/spec_helper.rb
Ticket :ticket: : https://openedx.atlassian.net/browse/TNL-2971
> Do not return standalone context threads for users

- models/content.rb
> Added last_activity_at index

- api/commentables.rb
- presenters/thread.rb
- spec/api/commentable_spec.rb
- spec/spec_helper.rb
MA-1359 Thread GET: returned resp_total for existing question and new thread
> ThreadAPI: returned resp_total for existing question and new thread

- api/comment_threads.rb
- presenters/thread.rb
- spec/api/comment_thread_spec.rb
- spec/presenters/thread_spec.rb
- spec/spec_helper.rb
MA-1189 ThreadGET - optionally include response comments via 'recursive' bool
> MA-1189 ThreadGET - optionally include response comments via 'recursive' bool

- config.ru
> Increased timeout back to 20s. Added comment

- api/comment_threads.rb
- spec/api/comment_thread_spec.rb
- spec/spec_helper.rb
MA-1190; Thread PUT -  update thread read status
> MA-1190; Thread PUT -  update thread read status

- api/comment_threads.rb
- spec/api/comment_thread_spec.rb
MA-1742; return read status on GET thread for user_id provided
> MA-1742; return read status on GET thread for user_id provided

- Gemfile
- Gemfile.lock
- README.rst
- Rakefile
- spec/spec_helper.rb
* Added Codecov to track test coverage
* Added an rspec rake task
FYI @macdiesel @wajeeha-khalid @BenjiLee
> Infrastructure Cleanup (Part 2)

- models/comment.rb
- models/comment_thread.rb
- models/content.rb
- spec/spec_helper.rb
- spec/support/database_cleaner.rb
- spec/support/elasticsearch.rb
- Cleaned model code
- Re-organized Elasticsearch and DatabaseCleaner rspec configuration
> Model and Spec Helper Cleanup

- Gemfile.lock
@clintonb @macdiesel will merge to fix CI and unblock some other folks.
> removing version data

- spec/spec_helper.rb
- Removed unused init_with_subscriptions
- Fixed spacing issues
> Updated spec_helper

- lib/tasks/db.rake
These tasks were broken by a previous commit (f959e2e). Given that no one has complained in over a month, I am removing them.
> Removed broken rake tasks

- Rakefile
- lib/task_helpers.rb
- lib/tasks/db.rake
- lib/tasks/search.rake
- spec/api/comment_thread_spec.rb
- spec/api/commentable_spec.rb
- spec/factories.rb
De-duplication, using factories, and other cleanup tasks.
> Updated specs

- Gemfile
- Gemfile.lock
@clintonb @macdiesel @maxrothman 
Looking to upgrade nokogiri.
> updating nokogiri

- Gemfile.lock
> Update newrelic plugin.

- models/comment_thread.rb
- spec/spec_helper.rb
TNL-3818 return thread's last_activity_at in response object for thread endpoints
> TNL-3818 return thread's last_activity_at in response object for thread endpoints

- Gemfile
- Gemfile.lock
@doctoryes @edx/devops 
Addresses security issues in libxml2.
> Upgrade nokogiri to address security issues in libxml2

- config/mongoid.yml
Updated the Mongoid configuration so that the read and write modes can
be specified via the `forum_env`.
> Updated the Mongoid configuration options

- app.rb
This was needed to give better visibility into issues on the box.  This fixes the transactions packaging to json.
Reviewers:
FYI: @dianakhuang
> Fix new relic traces.

- config.ru
@tobz: Adding a message just to make it more clear if this config is getting loaded.  You ok with this change?
> Add message for rack config load.

- .travis.yml
- Gemfile
This reverts commit 22178086b20246d82c5e6a9e38e27cdb13e6bef0, reversing
changes made to 14ed8a85c60245a7237d3fd0551b9f2c845e4e89.
> Revert "Merge pull request #196 from edx/platform/upgrade-to-ruby23"

- api/comment_threads.rb
- models/comment.rb
- models/comment_thread.rb
- presenters/thread_utils.rb
This adds tracing to `#to_hash` for `Comment` and `CommentThread`.  It also does a little clean up of query code.
> Add more tracing + code cleanup.

- models/user.rb
I didn't create a ticket for this, but just wanted to add some tracing to see more details in Production.
@tobz:  Can I get thumbs?
@dianakhuang: Do you want this to be more formal?
> Add method tracing inside user.

- lib/task_helpers.rb
- lib/tasks/search.rake
@robrap Could I get a quick review of this?
> Add error logging and batching to index-building.

- Rakefile
- lib/tasks/search.rake
Bring the rake search:rebuild fixes into ficus.
FYI: @nedbat
> TNL-6296: Fixes rake search:rebuild for ficus. (new)

- Rakefile
- app.rb
Already approved in PR https://github.com/edx/cs_comments_service/pull/227. Now merging directly onto master.
> Better filtering for rake search:initialize behavior

- api/search.rb
- api/users.rb
- lib/helpers.rb
- models/comment.rb
- models/comment_thread.rb
- models/user.rb
- presenters/thread.rb
- presenters/thread_utils.rb
@ormsbee @macdiesel @gsong @nedbat Not sure who best to tag here, so tagging all of you
> Wrap newrelic calls in a rescue block

- .travis/docker-compose-travis.yml
- Gemfile
- Gemfile.lock
- api/search.rb
- lib/task_helpers.rb
Upgrade to ES 1.x for forums.  I did update to slightly newer gems from @clintonb's original PR.
This will be a slightly long-lived branch used for testing in various environments until we are ready to merge and update multiple environments.
FYI: @clintonb
> [DELAY MERGE] TNL-6151: Upgrade forums to ES 1.x

- Gemfile
- Gemfile.lock
https://openedx.atlassian.net/browse/EDUCATOR-1912
> EDUCATOR-1912 | Upgrade yajl-ruby to 1.3.1

- api/users.rb
- models/comment.rb
- models/comment_thread.rb
- models/constants.rb
- models/content.rb
- models/user.rb
- spec/api/user_spec.rb
https://openedx.atlassian.net/browse/PLAT-2026
Support removal of forum content posted by a retired user.
Add tests for the new endpoint.
> Add user retirement API endpoint.

- api/users.rb
- models/constants.rb
- models/user.rb
- spec/api/user_spec.rb
https://openedx.atlassian.net/browse/PLAT-2125
Blank out comment thread documents as well as comment documents. Change the text used to replace the content. Ensure that comments are processed in tests.
> Fix forum retirement functionality.

- models/concerns/searchable.rb
https://openedx.atlassian.net/browse/PLAT-2164
The GDPR user retirement pipeline has experienced some rare issues with forum user retirement failing due to attempting to update a non-existent record in Elasticsearch. Adds error-handling around Elasticsearch updates/deletes.
> Add error handling around Elasticsearch update/delete.

- models/concerns/searchable.rb
- models/user.rb
- spec/models/comment_spec.rb
This defers any ES updates/callbacks during the mongo update phase for
each comment retirement, then attempts the ES update for all comments at
once using a bulk request.
PLAT-2310
---
Manual testing in devstack:
First PUT to create a dummy post (aka comment_thread):
```
PUT //content/comment_thread/5b9ab70d219038008f000000 HTTP/1.1
User-Agent: Faraday v0.12.1
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: */*
Connection: close
Host: edx.devstack.elasticsearch:9200
Content-Length: 682
Content-Type: application/x-www-form-urlencoded
{"_id":"5b9ab70d219038008f000000","abuse_flaggers":[],"anonymous":false,"anonymous_to_peers":false,"at_position_list":[],"author_id":"20","author_username":"retired8","body":"DELETE POST","closed":false,"comment_count":0,"commentable_id":"i4x-e …
```
> Process ES updates in bulk during user retirement.

- models/concerns/searchable.rb
- models/user.rb
- spec/models/comment_spec.rb
> Make sure ES stays enabled, even if there is an error during update()

- models/user.rb
- spec/api/user_spec.rb
We found out in prod that we did not sufficiently test the case of
retiring a user who did not make any forum posts at all.  In this case,
the forums code will send an empty bulk request to ES (bad).
PLAT-2310, still...
---
In summary, the spec changes does the following two things:
* Turns on ES during the retirement-related tests, to make sure we're covering all the possible failure modes.
* Adds one more test case which explicitly tests retiring an "inactive" user, i.e. a user with no forum posts.
> Avoid sending empty ES bulk requests

- Gemfile
- Gemfile.lock
Updated Mongo ruby driver
**Sandbox**
N/A
> Upgraded mongo ruby driver

- Gemfile.lock
Resolved the bson dependancy for mongo ruby driver
https://github.com/mongodb/mongo-ruby-driver/blob/v2.5.3/mongo.gemspec
**Sandbox**
N/A
> Resolved bson dependancy

- .travis.yml
- .travis/docker-compose-travis.yml
- Gemfile
- Gemfile.lock
- models/user.rb
Upgrade mongo db driver and and mongoid
**Sandbox**
https://test-ruby2.sandbox.edx.org/
> Upgrade mongodb ruby driver

- .travis.yml
- .travis/docker-compose-travis.yml
- Gemfile
- Gemfile.lock
- models/user.rb
Reverts edx/cs_comments_service#298
> Revert "Upgrade mongodb ruby driver"

- .travis.yml
- .travis/docker-compose-travis.yml
- Gemfile
- Gemfile.lock
- models/user.rb
Reverts edx/cs_comments_service#313
> Revert "Revert "Upgrade mongodb ruby driver""

- Rakefile
> Remove default rake to prevent data loss.

- Rakefile
> Make warning comment more specific.

- Gemfile
- Gemfile.lock
Update ruby gems with security vulnerabilities.
- **rake**
- **rack-protection**
> fix: update ruby gems to address security vulnerabilities.

- api/users.rb
- spec/api/user_spec.rb
The original code for returning course stats was broken and only works in the tests due to them testing in a database populated with only a single-course. This replaces it with an aggregation pipeline that will work in real-world scenarios.
> fix: replace user stats code with aggregation to allow sorting [INF-420] [BD-38]

- api/comment_threads.rb
- api/commentables.rb
- api/notifications_and_subscriptions.rb
- api/search.rb
- lib/helpers.rb
- spec/api/comment_thread_spec.rb
Adds a feature that allows filtering threads to only those that don't have a response.
> feat: Allow filtering threads by those that have not responses [INF-247] [BD-38]

- config/unicorn_tcp.rb
> Backport unicorn_tcp fork behavior fixes to Palm

- .github/workflows/ci.yml
Removing ruby 2 test pipeline.
> feat: remove ruby 2 pipeline

- catalog-info.yaml
- openedx.yaml
Added catalog file
Ticket: [INF-1486](https://2u-internal.atlassian.net/browse/INF-1486)
> chore: added catalog-info.yaml file and update openedx.yaml file
