AUTHORS, config/mongoid.yml
Makes it possible to use SSL for the mongo connections by setting the `MONGOID_USE_SSL` environment variable to `True`.
*Background*: A third-party Open edX installation for Harvard is using an externally hosted mongo cluster. Due to security policies, the connections from cs_comments_service to the mongo cluster are required to be encrypted. Mongoid supports ssl connections by setting the `ssl` parameter to true when initializing a connection. This change makes it possible to initialize PyMongo/Mongoid connections so that they are use SSL encryption by setting an environment variable (which is in turn set up by edx/configuration, see https://github.com/edx/configuration/pull/1944).
*Partner information*: Harvard, for a third-party Open edX installation
*Jira ticket*: …
=> Add ability to set ssl option through env variable.

api/comment_threads.rb
@jimabramson Please review
For some reason, there's a separate pin endpoint that enforces that a user_id parameter is provided, even though it's not actually used for anything. I see no reason pinned and closed should have different behavior, so this just allows pinned to be set via a PUT just like closed.
=> Allow pinned field to be updated via PUT

AUTHORS, api/commentables.rb, api/search.rb, lib/helpers.rb, models/comment.rb, models/comment_thread.rb, scripts/db/migrate-008-context.js, scripts/db/revert-migrate-008-context.js, spec/api/comment_thread_spec.rb, spec/api/commentable_spec.rb, spec/api/search_spec.rb, spec/spec_helper.rb
This PR introduces a `context` field on the `CommentThread` model. Currently, context can be `course` or `standalone`. `course` is the normal value, and indicates that the thread is part of general course discussions. `standalone` indicates that the thread is separate from general course discussion and should only be returned if explicitly requested. Context can be specified when creating threads associated with commentables by passing an extra parameter. Context can also be specified when retrieving threads associated with a commentable by passing a parameter. https://github.com/edx/edx-platform/pull/8982 uses this field.
@cahrens @dan-f please review.
=> TNL-1943 Add context field to CommentThread

scripts/db/migrate-008-context.js
The bulk operation should be faster and more performant than doing the db.find.update
Docs here: http://docs.mongodb.org/v2.6/reference/method/Bulk.find.update/
@dianakhuang @macdiesel
=> Use bulk operation instead.

config.ru
@jimabramson Any reason this needs to be 20? The django comment client's timeout is 5 seconds.
https://github.com/edx/edx-platform/blob/master/lms/lib/comment_client/utils.py#L85
FYI @macdiesel in case you had an opinion.
=> changed timeout to 6 seconds

AUTHORS, Gemfile, Gemfile.lock, Rakefile, api/comments.rb, api/search.rb, api/users.rb, app.rb, config.ru, config/mongoid.yml, config/unicorn.heroku.rb, config/unicorn.rb, config/unicorn_tcp.rb, lib/helpers.rb, models/comment.rb, models/comment_thread.rb, models/notification.rb, models/subscription.rb, models/user.rb, presenters/thread_utils.rb, spec/api/abuse_spec.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/api/commentable_spec.rb, spec/api/notifications_spec.rb, spec/api/query_spec.rb, spec/app_spec.rb, spec/spec_helper.rb
All tests passing on mongodb 3.x installed locally. We will need to run a load test on this as the Identify mapping (caching) functionality was dropped from mongoid in the 4.x version.
=> Update Mongoid to 5.x release (mongodb 3.x + compatibility)

.travis.yml, AUTHORS
The bundler version on Travis is outdated and has issues installing the gems. Updating to latest version.
=> Updating bundler on Travis

.travis.yml, spec/api/comment_spec.rb
Running these services as daemons so that we can take advantage of Travis' container-based infrastructure. One test had to be updated, most likely due to sorting not behaving as expected. All tests will be updated in the future to properly prepare test data, and not rely on sorting/querying.
=> Running MongoDB and Elasticsearch as daemons

Gemfile, Gemfile.lock, spec/api/abuse_spec.rb, spec/api/comment_spec.rb, spec/api/i18n_spec.rb, spec/api/query_spec.rb, spec/factories.rb, spec/spec_helper.rb, spec/support/factory_girl.rb
This is the start of some much-needed test cleanup. Factories are replacing various helper functions used to generate test data. These functions generate far more data than the tests actually need. This results in slower test execution times due to the need to read/write/destroy this data in both Mongo and Elasticsearch.
These changes cut the Travis run time down from ~13 minutes to ~7 minutes. Future changes in #165 (especially those to `search_spec.rb`) should decrease this time even further.
=> Added factories and updated specs

Rakefile, lib/task_helpers.rb, lib/tasks/db.rake, lib/tasks/search.rake, spec/factories.rb
- Cleaned up quotes
- Using factories to generate seed data
- Moved Elasticsearch functions into helper module
This is prep work for #165. The more code that can be cleaned prior to that merge, the simpler the review of the Tire switch.
=> Refactored rake tasks

api/comment_threads.rb, api/users.rb, spec/api/comment_thread_spec.rb, spec/api/user_spec.rb
Update Thread PUT to make 'read' field mutually exclusive to other update fields.
For thread PUT requests;
- update last activity date for thread field updates.
- do not update last activity date if PUT request is made to mark thread as read
=> MA-2419:threadPUT - make 'read' mutually exclusive to other fields

models/comment.rb, spec/models/comment_spec.rb
[TNL-4944](https://openedx.atlassian.net/browse/TNL-4944)
Add more error-checking when getting the parent comment thread for comments.
=> Handle comment context in cases of missing parent thread.

.travis.yml, Gemfile, Gemfile.lock, spec/support/database_cleaner.rb, spec/support/factory_girl.rb
Now that we're on MongoDB 3.0 in production, we should also be testing with MongoDB 3.0.
=> Switch to using MongoDB 3.0 in tests.

.travis.yml
Now that MongoDB 3.0 seems to download/untar faster than 2.6, we seem to be right over the line of how quickly ES can start up and be listening for connections, which leads the tests to try and connect too quickly, which fails.
By sleeping for 10 seconds after starting ElasticSearch, it's almost a certainty it will be up and running by the time we try to first connect to it.
=> Wait 10s after starting ElasticSearch.

models/comment.rb
Some of the ways comments are accessed in the User model (when a complete user object is requested) lead to an N+1 situation because while we preload the related documents (preloading the parent thread of a given comment, in this case), further accesses to those comments actually never take advantage of the preloaded relations.
We should be using the relation directly, which will still act the same as before but allow us to actually benefit from preloading.
=> Use proper relations instead of forcefully loading relations by hand.

.travis.yml, Gemfile
Pretty self-explanatory.  Will require a corresponding change in edx/configuration if accepted / deployed.
=> Upgrade to Ruby 2.3.0

models/user.rb, spec/api/user_spec.rb, spec/models/user_spec.rb, spec/spec_helper.rb
Use pluck instead of map for upvoted/downvoted IDs.
Mapping involves doing the projection locally, whereas plucking will ask MongoDB to do the projection for us.  This is the difference between sending the whole document back and sending back the ObjectId itself.
Multiplied against hundreds or thousands of documents, mapping can really add up, so plucking should really help these 99%'ile cases.
=> Plucking instead of mapping.

models/comment.rb, models/comment_thread.rb, presenters/thread_utils.rb, scripts/db/migrate-009-comment_thread-author-created_at-indexes.js, spec/api/comment_thread_spec.rb, spec/api/search_spec.rb, spec/spec_helper.rb
[MA-2678](https://openedx.atlassian.net/browse/MA-2678)
To calculate 'read' status;
- for posts used 'last_acitvity_at' instead of 'updated_at'.
- for responses/comments used 'created_at' instead of 'updated_at'
Changed post/response/comment behaviour to update 'last_activity_at' only at time of creation.
Added a new index in migration script.
`db.contents.ensureIndex({ comment_thread_id: 1, author_id: 1, created_at: 1 }, { background: true })`
P.S:
Adding the new index in load test `create_indexes.js` is part of another PR https://github.com/edx/edx-load-tests/pull/62 which will be used for performance testing and the results of tests should be accepted before merging this PR.
cc: @BenjiLee
=> MA-2678: replace use of 'updated_at' for 'read' state

api/comment_threads.rb, lib/helpers.rb, presenters/thread.rb, spec/api/comment_thread_spec.rb
For cases where we don't need or want the responses on a thread at all, like getting some metadata about a thread, we should be able to request it without the responses.  This exists in the `ThreadPresenter` but didn't exist as an option that could be passed in the API call itself.
We've added this as an option now -- `with_responses` -- that defaults to `true`, which preserves the existing behavior but does in fact allow toggling.
This gives us a backwards-compatible upgrade path to allow changes to be made the LMS so that requests which don't need the responses, or do need the responses, can be explicit about what they want.
=> Add the ability to request a thread without its responses.

api/comment_threads.rb, api/commentables.rb, api/comments.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/api/commentable_spec.rb, spec/spec_helper.rb
Mark thread as read on thread and comment creation for leaner himself.
=> MA-2139: Mark thread as read for leaner on thread/comment creation

api/comment_threads.rb, api/commentables.rb, api/notifications_and_subscriptions.rb, api/search.rb, lib/helpers.rb, lib/tasks/benchmark.rake, lib/tasks/deep_search.rake, spec/api/comment_thread_spec.rb, spec/api/search_spec.rb
[TNL-5115](https://openedx.atlassian.net/browse/TNL-5115)
Sort order was not indexed appropriately for ascending order, and we always used descending, so this parameter is being removed from the product.  
This PR removes this completely from the cs_comment_service code. 
=> TNL-5115: Remove sort order from cs_comment_service

api/comment_threads.rb, config/application.yml, locale/en-US.yml, locale/x-test.yml, spec/api/comment_thread_spec.rb, spec/presenters/thread_spec.rb, spec/spec_helper.rb
By default, we currently allow a user to retrieve all responses from a thread, which is terrible from a performance standpoint.
This change adds a default response size of 100, which was chosen to match typical production pagination parameters, and a response limit of 200.  Given that responses can include children comments, 200 is still a large number, but far less disastrous than, say, getting 3000 responses, with all of their children comments.
Both of these values are configurable.
Before we deploy checklist:
=> Add a default response size and a response size limit.

.travis.yml, .travis/run_tests.sh, config/mongoid.yml, docker-compose-travis.yml
@bilalahmad99 Here is how far I got.  I'm going to try to catch up with you early our morning, middle of your day I think. But feel free to merge this so you can work on top of it.  The biggest changes is making the elasticsearch and mongo services come up in their own containers in docker-compose.  The containers get addresses based on their names which mostly match the defaults.  I had to tweak how the forums pull in the config for testing so it works correctly.  This is working for me locally but may need tweaks to get fully done in travis.
=> Run tests using the es and mongo containers with docker-compose.

.travis.yml, .travis/run_tests.sh
The core issue was that if you don't provide an install step travis
tries to do its default action which generates a bunch of ruby code
that is linked to the ruby on the host system instead of the ruby in
the container.
=> Make the ruby linking error go away.

lib/tasks/search.rake
This change fixes a small typo in the `search:reindex` rake task.
**Deployment targets**: edx.org and edge.edx.org
**Merge deadline**: ASAP - want to get into the Ficus release candidate.
1. On your edxapp devstack, checkout this branch under `cs_comments_services`.
1. Run:
```
vagrant@precise64:~$ sudo su forum
forum@precise64:~/cs_comments_service$ rake search:rebuild
```
Should complete without error.  Without this patch, the following error is displayed: 
```
forum@precise64:~/cs_comments_service$ rake search:rebuild
/edx/app/forum/cs_comments_service/lib/tasks/flags.rake:6: warning: already initialized constant ROOT
/edx/app/forum/cs_comments_service/lib/tasks/kpis.rake:7: warning: already initialized constant ROOT …
```
=> Fix typo in search:do_reindex task

Rakefile
There are fixes needed for ES that existed in app.rb, that weren't loaded in the Rakefile environment.  Rather than attempt to pick and choose, which may lead to future errors of this sort, this just naively loads app.rb from Rake.
This means that:
1. We need special code in the newer PR to [skip code in app.rb when initializing the index](https://github.com/edx/cs_comments_service/pull/216/commits/8f2cd94cc1544f7863c15599809855af649ed35f).
2. We are definitely loading code that we don't need for Rake.
3. Do we need to retest all of Rake tasks using rake itself?  If this works, it seems simpler than either duplicating code (as was done before) or creating some other common rb file to load into both, which may lead to the same kind of bug if code is put in the wrong place.
Thoughts? …
=> TNL-6118: Fix rebuild by loading app.rb in Rakefile

lib/task_helpers.rb, lib/tasks/search.rake, spec/lib/tasks/search_rake_spec.rb
Minor changes to rebuild_index rake task:
- Default to moving alias and running catchup.
- Allow configurable extra minutes for catchup.
- skipping unless a reviewer wants this.
=> TNL-6464: Minor changes to rebuild_index.

.travis/run_tests.sh, README.rst, Rakefile, app.rb, lib/task_helpers.rb, lib/tasks/search.rake, models/concerns/searchable.rb, spec/lib/task_helpers_spec.rb
The original intent of this code was to make search:initialize idempotent.  
Additionally, we added rake tasks for:
- validate_index (used to validate index and mappings)
- put_mappings (used to potentially update mappings on an existing index)
FYI: @clintonb
=> TNL-6447: Make search:initialize idempotent.

config/unicorn.rb, config/unicorn_tcp.rb, lib/unicorn_helpers.rb, spec/lib/unicorn_helpers_spec.rb, spec/support/matchers.rb
Run the rake search:validate task before starting the service. If it
fails, then that means the mappings or indexes aren't in sync, the
former of which can cause corrupt data, and the latter, non-functioning
search. It fails with this exit code so that supervisor knows whether to
sleep before trying to restar the app or not.
Should merge simultaneously with https://github.com/edx/configuration/pull/3689
=> Verify that ES is configured properly before starting

lib/task_helpers.rb
In manual testing, I found two cases where it would be useful to have an extra INFO log:
1. `rake search:validate_index` when it passes.
2. `rake search:initialize` when it is skipping due to existing index.
=> TNL-6562: Enhance rake logging.

Gemfile, Gemfile.lock
[NewRelic have dropped support for ruby 1.9.x](https://discuss.newrelic.com/t/support-for-ruby-jruby-1-x-is-being-deprecated-in-ruby-agent-4-0-0/44787), and so we can't use their latest app monitoring agent until we upgrade ruby.
This change fixes the version to `newrelic_rpm (3.16.0)`, which is needed until the ruby 2.x upgrade is complete (planned for [Gingko](https://openedx.atlassian.net/wiki/display/COMM/Ginkgo)).
**JIRA tickets**: [OSPR-1688](https://openedx.atlassian.net/browse/OSPR-1688)
**Sandbox URL**:
* LMS: https://forums-pr237.sandbox.opencraft.hosting/
* Studio: https://studio-forums-pr237.sandbox.opencraft.hosting/
**Deployment targets**: edx.org and edge.edx.org
**Merge deadline**: ASAP - New Relic drops support at the end of February 2017.
1. …
=> Install newrelic_rpm to < 4.0

config/mongoid.yml
The service is no longer authorized to edit a database of a different name,
so this changes the development database name to match the name of
other environments.
FYI: @jlajoie @feanil
=> Update development db to match others.

config/unicorn.rb, config/unicorn_tcp.rb
When trying to launch the app if the `LOAD_PATH` was not properly set
the unicorn server was unable to load the `app.rb` source
file. Updated to use the `expand_path` method from the File class.
This PR replaces #245.
=> Fixed issues with app.rb require

api/users.rb, spec/api/user_spec.rb
Fix for: https://openedx.atlassian.net/browse/EDUCATOR-2854
=> Handle non-existent user and missing param upon retiring user.

app.rb
We suspect newrelic is not being loaded because the "newrelic_rpm" group
is not being specified.  We cannot blindly load it because the open
source community rightly demands independence from newrelic, so we
conditionally load it.
=> require the newrelic_rpm group when NEW_RELIC_ENABLE is set

.travis.yml
I've been working on adding some automation for creating and testing openedx releases, which creates branches in a number of IDA's, and (if desired) deletes them at the end of the tests. For now, the job is in the beginning stages, and just creates a branch, and later deletes it.
The problem is, the branch gets deleted so quickly, that travis gets kicked off, but quickly fails when the branch can't be found. To make matters worse, since the branch doesn't include any new commits, travis gets run (and fails) on the same commit as the tip of the master branch, which overwrites whatever status it previously had to failing (example: link to failing travis build).
This change fixes that, by following a travis pattern we currently already use in other repos, like these: (configuration repo, …
=> Build travis push on master only

AUTHORS, Gemfile.lock
Update NewRelic on forums. 
As NewRelic_Rpm was not pinned to any specific version, I  just have to run the `bundle update newrelic_rpm` to update to the latest version of newrelic gem. 
As I do not have much context about ruby and its gems, I am going to ask for the Cambridge review.
=> Update new relic

Gemfile.lock
On one of our AWS instances, forum service is failing with errors like the following when a request is made to it:
```
/edx/app/forum/.gem/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_request.rb:80:in `parse': method `hash' called on unexpected T_IMEMO object (0x0055c77a4c6b60 flags=0x707a) (NotImplementedError)
--
from /edx/app/forum/.gem/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_request.rb:80:in `read'
from /edx/app/forum/.gem/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:606:in `process_client'
from /edx/app/forum/.gem/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:702:in `worker_loop'
from /edx/app/forum/.gem/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
from …
```
=> [SE-886] Upgrade unicorn to 5.3.1 to fix GC error

Gemfile, lib/helpers.rb
'handle_threads_query' helper method optimized to increase performance. Previously it was fetching count of collection thrice and that was costly operation when performed on big comments/threads collection. Optimized code now fetches count only once. 
YONK-1177 contains all the details.
=> handle_threads_query helper method optimized to increase performance

config/mongoid.yml
Allows specifying an `auth_source` parameter for MongoDB. 
This can be configured via: https://github.com/edx/configuration/pull/5195
A similar PR for edx-platform: https://github.com/edx/edx-platform/pull/20819
=> [BB-1289] Add support for configuring auth_source for Mongo connection

Gemfile, Gemfile.lock
Reverts edx/cs_comments_service#287
Forums are not working on stage after merging this PR.
Error: "undefined method `select_server' for {"mode"=>:primary}:BSON::Document"
This error was supposed to be fixed in version 2.5 but it seems to be occurring in 2.11 as well.
https://jira.mongodb.org/browse/RUBY-1235
New relic errors:
=> Revert "Upgraded mongo ruby driver"

Gemfile, Gemfile.lock
Updated Mongo ruby driver to version 2.5.3 to make it compatible with mongo 3.6. Upgrading to the latest 2.11 causes a lot of failures as there are major changes in that version.
I tried upgrading it to in between versions as well but it turns out that the ruby version (2.4) we are using is supported until Mongo ruby driver 2.5.3.
**Sandbox**
N/A
=> Updated mongo ruby driver

Gemfile, Gemfile.lock
Revert upgrade mongo db ruby driver. The driver was upgraded to 2.5.3 which is the earliest version that is compatible with mongo 3.6 but it is still producing errors on stage.
**Sandbox**
N/A
=> Revert upgrade mongo ruby driver

lib/helpers.rb
Fix cursor not found error caused during mongodb driver upgrade.
The previous [PR](https://github.com/edx/cs_comments_service/pull/298) was merged and deployed to stage but there are some errors there. I have looked into the details of the error. There seems to be only one endpoint that is causing an issue.
New Relic Error:
https://rpm.newrelic.com/accounts/88178/applications/3343672/traced_errors/f0806c1f-53ab-11ea-a5a4-0242ac110008_34611_41003
I have looked into the details of the error trace and also tried to reproduce the issue locally but it is not reproducible.  The endpoint with the issue is covered by test cases as well and there are no test failures. 
Looking into the details of the error it seems it is being caused during a mongo db operation and I have searched a bit about it …
=> Fixed mongo cursor not found

lib/helpers.rb
Reverts edx/cs_comments_service#308
=> Revert "Fixed mongo cursor not found"

.travis/docker-compose-travis.yml, config/mongoid.yml
Allows the mongo client's `auth_mech` to be configured from the environment and via ansible.
**JIRA tickets**: [CRI-186](https://openedx.atlassian.net/browse/CRI-186), [OSPR-4402](https://openedx.atlassian.net/browse/OSPR-4402), [SE-2321](https://tasks.opencraft.com/browse/SE-2321)
**Discussions**: [Discussion forum errors in latest master with mongo 3.2](https://discuss.openedx.org/t/discussion-forum-errors-in-latest-master-with-mongo-3-2/1843/5)
**Dependencies**: Relates to https://github.com/edx/configuration/pull/5755
**Sandbox URL**:
* LMS: https://forumpr316.sandbox.opencraft.hosting/
* Studio: https://studio.forumpr316.sandbox.opencraft.hosting/
**Merge deadline**: ASAP, fix needed for Juniper.
Devstack:
1. Check out this branch under your …
=> CRI-171 Makes the mongo authentication mechanism configurable from the environment

Gemfile.lock
Codecov 0.1.x was yanked from rubygems, causing installation of cs_comments_service to fail. This bumps to the latest codecov version.
=> bump version codecov to latest release

.travis/docker-compose-travis.yml, .travis/elasticsearch.yml, Gemfile, Gemfile.lock, README.rst, api/search.rb, config/application.yml, lib/task_helpers.rb, lib/tasks/search.rake, lib/unicorn_helpers.rb, models/comment.rb, models/comment_thread.rb, models/content.rb, models/user.rb, spec/api/query_spec.rb, spec/api/search_spec.rb, spec/lib/task_helpers_spec.rb, spec/lib/tasks/search_rake_spec.rb, spec/lib/unicorn_helpers_spec.rb, spec/spec_helper.rb, spec/support/elasticsearch.rb
**Description**: 
Updates versions of the ES and the ES DSL libs from V1.5.2 to V7.8.0
Splits content index with comment and comment_thread doc_types to comment and comment_thread indices. 
**Was done**:
update ES libs version;
rewrite index documents for compatibility with ES7;
update make commands;
update travis ci.
**Current code coverage**: 95.78%.
**Reviewers**:
@mikix
@dianakhuang
**Post merge**:
- Delete working branch
=> [BD-19] Transition to the new Elasticsearch libs version for cs_comments_service

api/comment_threads.rb
Make the importance of the sort_key more clear in case it confuses
others in the future that the posts are not coming back in order from
most comments to least number of comments.
=> Add a comment.

api/users.rb, app.rb, models/user.rb, mongoutil.rb, spec/app_spec.rb
The forum process stops working after a MongoDB replica failover, even when the MongoDB Ruby driver connects using read modes that allow for reading on secondaries.
After some investigation we found that there's a piece of Ruby code that ensures the server connected is the primary and returns a database failure in case it is not.
The approach was changed instead to reconnect to the primary during a heartbeat or when writing to MongoDB.
**Merge deadline**: ASAP
1. Check the [extended heartbeat](https://mongo-failover.opencraft.hosting/heartbeat?extended) to ensure everything works.
1. Request a failover (or SSH into the VM and use `rs.stepDown()` on a mongo shell connected to the primary local mongodb).
1. Create a new user to access the discussions, to ensure the …
=> Reconnect MongoDB after failover

.github/docker-compose-ci.yml, api/users.rb, spec/api/user_spec.rb
Adds a new API that returns the following stats about a user's participation in a course's discussion:
- The number of threads they have created.
- The number of responses they've posted on threads. 
- The number of replies they've made to responses. 
- The number of active flags/reports against the user.
- The number of inactive flags/reports against the user.
**JIRA tickets**: https://openedx.atlassian.net/browse/TNL-8795
**Dependencies**: 
1. Create a course with a set of users.
2. Make posts as different users, add responses and replies, and mark a few posts, comments, threads etc as flagged.
3. Unmark a few flags.
4. Check the API response and make sure it seems correct. 
5. Compare to the existing single-user API for this.
**Author notes and concerns**: …
=> feat: Add user course stats API [BD-38] [TNL-8795] [BB-4970]

api/users.rb, spec/api/user_spec.rb
Returns the username in addition to author id in the course user stats API.
=> feat: return username from user stats API [BD-38] [TNL-8795] [BB-4970]

api/comment_threads.rb, api/comments.rb, lib/helpers.rb, presenters/thread.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/spec_helper.rb
Add a new endpoint to retrieve comments from an user in a specific course.
* `/api/v1/comments?user_id=<user_id>&course_id=<course_id>`
* `/api/v1/comments?user_id=<user_id>&course_id=<course_id>&flagged`
1. Setup a master devstack
2. Checkout this branch
3. Restart `cs_comments_service`
4. Post a few comments in the Discussions area with a test user
5. Retrieve the user's comments by calling the API with the user's and the course's IDs.
Example:
```bash
curl -H "X-Edx-Api-Key: password" "http://localhost:44567/api/v1/comments?user_id=1&course_id=course-v1:edX+DemoX+Demo_Course"
```
FYI -- @ormsbee & @benmcmorran
=> Add new filters to the comments API [BD-38] [TNL-8796] [BB-4969]

api/comment_threads.rb, api/comments.rb, models/comment.rb, models/comment_thread.rb, models/constants.rb, models/edit_history.rb, models/user.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/spec_helper.rb
Adds support for specifiying an optional edit reason when editing a post which is preserved when the post is edited by a user that isn't the original author (for instance a moderator). The edit reason can be used by the platform to indicate why a post or comment was changed, for instance if it contained answers. It also stores the user that made this change and retains the previous version of the body in this case.
It also adds support for a post close reason code. This can be specified when closing the post. The user closing a post is also tracked as closed_by.
=> feat: Add support for specifying edit and close reasons [BD-38] [TNL-8842] [BB-5011]

.gitignore, api/users.rb, lib/helpers.rb, models/comment.rb, models/comment_thread.rb, models/user.rb, spec/api/notifications_spec.rb, spec/api/user_spec.rb
In a previous PR (https://github.com/edx/cs_comments_service/pull/352) we introduced a new API that would generate user stats for a course on-the-fly. The query would return data about all the users in a course who'd participated in discussions. In some cases, this could be in hundreds of thousands or millions of users, and result in dozens if not hundreds of MBs of data. 
This data also needed to be sorted, and paginated. Due to the nature of the query, paginating this data would not reduce the performance implications of the query, since it'd still need to query all the course data to build the stats. That said, it would reduce the final amount of data involved.
This PR implements a different mechanism for the same. It will keep track of user counts across courses, by incrementing the …
=> feat: keep cached user stats [BD-38]

spec/api/abuse_spec.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/api/commentable_spec.rb, spec/api/i18n_spec.rb, spec/api/notifications_and_subscriptions_spec.rb, spec/api/notifications_spec.rb, spec/api/query_spec.rb, spec/api/search_spec.rb, spec/api/user_spec.rb, spec/api/vote_spec.rb, spec/app_spec.rb, spec/lib/task_helpers_spec.rb, spec/lib/tasks/search_rake_spec.rb, spec/lib/unicorn_helpers_spec.rb, spec/models/comment_spec.rb, spec/models/comment_thread_spec.rb, spec/models/user_spec.rb, spec/presenters/thread_list_spec.rb, spec/presenters/thread_spec.rb, spec/support/matchers.rb
This conversion is done by Transpec 3.4.0 with the following command:
transpec
* 294 conversions
from: obj.should
to: expect(obj).to
* 240 conversions
from: == expected
to: eq(expected)
* 15 conversions
from: it { should ... }
to: it { is_expected.to ... }
* 11 conversions
from: obj.stub(:message)
to: allow(obj).to receive(:message)
* 9 conversions
from: obj.should_not
to: expect(obj).not_to
* 6 conversions
from: obj.should_receive(:message)
to: expect(obj).to receive(:message)
* 1 conversion
from: >= expected
to: be >= expected
* 1 conversion
from: failure_message_for_should { }
to: failure_message { }
* 1 conversion
from: failure_message_for_should_not { }
to: failure_message_when_negated { }
* 1 conversion
from: lambda { }.should
to: expect { }.to
* 1 conversion
from: lambda { …
=> Convert specs to RSpec 3.6.0 syntax with Transpec

Gemfile, Gemfile.lock
Update ruby gems with security vulnerabilities.
- nokogiri
- rubyzip
=> fix: update nokogiri and rubyzip gems for security

Gemfile, Gemfile.lock
Update ruby gems with security vulnerabilities.
- **ffi**
- **faye-websocket**
- **addressable**
- **activesupport**
- **activemodel (done as this is a dependancy)**
=> fix: update Ruby gems to fix security vulnerabilities.

api/comment_threads.rb, api/comments.rb, models/comment.rb, models/comment_thread.rb, models/constants.rb, models/edit_history.rb, models/user.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb, spec/spec_helper.rb
Adds support for specifiying an optional edit reason when editing a post which is preserved when the post is edited by a user that isn't the original author (for instance a moderator). The edit reason can be used by the platform to indicate why a post or comment was changed, for instance if it contained answers. It also stores the user that made this change and retains the previous version of the body in this case.
It also adds support for a post close reason code. This can be specified when closing the post. The user closing a post is also tracked as closed_by.
Note: Was previously merged as #356 but that changed the API in a way that broke the legacy UI.
=>  feat: Add support for specifying edit and close reasons [BD-38] [TNL-8842] [BB-5011] 

lib/helpers.rb
A bug in the `handle-threads_query` code meant that the filter for followed threads didn't work if a thread type wasn't also specified. This change fixes that.
=> fix: following filter didn't work if no thread type was specified [BD-38] [TNL-9609]

api/comment_threads.rb, api/comments.rb, spec/api/comment_spec.rb, spec/api/comment_thread_spec.rb
The closing and editing users now need to be manually specified since the default is to use the author.
Also adds support for sorting user comments by flagged status.
=> feat!: Use explicitly-specified user ids for closing and editing users, and add sorting by flags [BD-38] [TN-9809]

api/users.rb, spec/api/user_spec.rb
Adds support to the user course stats API to fetch data only for users specified in the username param.
=> feat: add support for fetching course stats for specific users [BD-38] [INF-298] 

models/user.rb, scripts/db/migrate-010-user-course_stats-course_id-index.js, scripts/db/revert-migrate-010-user-course_stats-course_id-index.js
The query to look up users by which ones have a course stat for a particular course is very slow when there are a large number of courses and users. This change adds an index for that field so that looking up users based on their course stats should be much faster.
=> fix: add index for course id in user stats [BD-38]

api/users.rb, lib/helpers.rb, spec/api/user_spec.rb, spec/spec_helper.rb
This commit adds support for filtering the active threads endpoint using the same parameters that can be used to filter the all threads endpoint.
**Note:**
This changes the way sorting and pagination works with this API. Since this is an API used by the legacy experience as well, that would impact the existing experience. 
Here's what's changed:
- The new pagination no longer supports arbitrarily large page numbers. i.e. you can't ask for page number 10,000 and get a result unless there are actually 10,000 pages. Earlier, it would return the last page in such cases. 
- Earlier, the threads would be sorted by the latest activity by the user. Now it can no longer be sorted that way, instead it is sorted by latest activity by **any user**. In order to support ordering the old way, the …
=> feat: Add support for filtering active threads using the same params as all threads [BD-38]

Gemfile, Gemfile.lock, api/users.rb, models/comment.rb, models/comment_thread.rb, models/user.rb, spec/api/user_spec.rb
Each time a user edits a thread or comment, update their activity timestamp so their course activity statistics include their lastest activity timestamp.
=> feat: Maintain last activity timestamps for users so stats can be sorted on that basis [BD-38] [INF-251]

api/users.rb
Adds support of the `count_flagged` query parameter to the Discussions learner threads endpoint. 
- Depends on https://github.com/openedx/edx-platform/pull/31048.
This has to be used in conjunction with https://github.com/openedx/edx-platform/pull/31048, so use test instructions from there.
=> [BD-38][BB-6681] feat: add support of the `count_flagged` query param to the learner threads endpoint

api/users.rb, spec/api/user_spec.rb
The user stats API had a few issues that were breaking pagination. First of all the total count of entries was reported
as the count after limiting to the per-page limit. This meant that the count would be limited to the page count even
if there were more entries. This commit adds a facet to the query that fetches the total count, and the data after
limiting. Another issue was using skip after limit, which is the incorrect order. This commit fixes that.
=> fix: pagination for user stats api [BD-38]

api/users.rb, lib/helpers.rb, spec/api/user_spec.rb
When using the default `user_activity` filter for the active threads API, the
pagination and sorting happens in Ruby instead of MongoDB. In addition, when
using the unread filter, the pagination mechanism is different. This code
introduces a fix for when they are both used together.
=> fix: pagination behaviour of user active threads API [BD-38]

api/comment_threads.rb, lib/helpers.rb, presenters/thread.rb, spec/presenters/thread_spec.rb, spec/spec_helper.rb
- Added `reverse_order` query parameter to the threads endpoint.
- Modified `merge_response_content` to support reversed content order.
1. Open Discussion for some course.
2. Create a discussion, add two responses, add comments for both of them.
3. Specify the thread ID (you can find it in the address bar) and course ID, and run the following ([httpie](https://github.com/httpie/httpie) used):
```
http http://127.0.0.1:4567/api/v1/threads/<YOUR_THREAD_ID> "X-EDX-API-KEY: forumapikey" course_id==<YOUR_COURSE_ID> with_responses==True user_id==4 mark_as_read==False recursive==True resp_skip==0 reverse_order==false
```
You should see a thread with comments ordered by the creation date.
4. Run the command from the previous point, but change `reverse_order==false` to `reverse_order==true`. You …
=> [BD-38][INF-544][BB-6682] feat: implement reverse_order parameter

api/comment_threads.rb, api/users.rb, lib/helpers.rb, presenters/thread.rb, spec/api/user_spec.rb, spec/presenters/thread_spec.rb, spec/spec_helper.rb
Merge master into the Olive branch.
=> Sync to master

api/search.rb, app.rb, config/application.yml, lib/task_helpers.rb, models/comment.rb, models/comment_thread.rb, spec/lib/task_helpers_spec.rb, spec/lib/tasks/search_rake_spec.rb
Adds a new configuration setting, `ELASTICSEARCH_INDEX_PREFIX`. If set, all Elasticsearch indexes and aliases that are generated by the application begin with the prefix.
This is to enable multi-tenancy, so that more than one version of this application can run on an ElasticSearch deployment.
When testing this, be sure to clear out your current `tutor` install beforehand (`tutor local stop` and `rm -r ~/.local/share/tutor`)
- Update your tutor version to at least 14.2.0: `pip install --upgrade tutor[full]`
- Install the tutor-forum plugin: `pip install git+https://github.com/open-craft/tutor-forum@keith/prefix-elasticsearch-indexes`
- Enable the plugin `tutor plugins enable forum`
- ```
tutor config save --set ELASTICSEARCH_INDEX_PREFIX=starting_ \
--set …
```
=> feat: operators can prefix elasticsearch indexes for multi-tenancy

config/unicorn_tcp.rb
Updated the unicorn_tcp before_fork and after_fork behaviors to be consistent with mongodb documentation.
See closed PR: [#406](https://github.com/openedx/cs_comments_service/pull/406)
@ MIT Office of Digital learning we use managed MongoDB Atlas as our backend datastore. Because of that, we don't always have visibility when maintenance events take place in the MongoDB cluster. We recently migrated `cs_comments_service` (we call it `forum`) to docker containers and we began noticing that when a MongoDB maintenance event takes place, the forum application becomes non-responsive until the docker container is restarted, which generally requires a manual intervention. 
We are able to recreate this by manually triggering a primary failover in Atlas, and then observing the forum's behavior …
=> fix: Updated the unicorn_tcp fork behavior

api/notifications_and_subscriptions.rb, spec/api/notifications_and_subscriptions_spec.rb
https://2u-internal.atlassian.net/browse/INF-943
added subscribers in thread object
=> feat: added API to get subscribers of a thread.

api/users.rb, spec/api/user_spec.rb
API was returning 500 when there were no stats in a course.
Ticket Link: [INF-1067](https://2u-internal.atlassian.net/browse/INF-1067)
=> fix: 500 error if paginated_stats are empty

models/user.rb, spec/api/user_spec.rb, spec/spec_helper.rb
[INF-887](https://2u-internal.atlassian.net/browse/INF-887)
When a user makes their first non-anonymous post, the system uses the "build_course_stats" function to create a new set of statistics for that user. However, there is a problem with the current implementation of the function. It counts all the posts made by a specific user, including those that are anonymous or were made anonymously to peers, before the user made their first non-anonymous post. This leads to an inaccurate count of the user's threads being saved in the database. In other words, the function doesn't filter out the posts made before the user started posting non-anonymously, causing the stored count to be incorrect.
Note: this fix is not backward compatible as that would require direct changes to the database.
=> fix: exclude anonymous posts in build_course_stats

.github/workflows/codeql-analysis.yml
I noticed code scanning now supports Ruby, so I'm putting up this PR for review.
=> feat: Enable code scanning

api/comment_threads.rb, presenters/thread.rb, spec/api/comment_thread_spec.rb, spec/presenters/thread_spec.rb, spec/spec_helper.rb
[INF-1240](https://2u-internal.atlassian.net/browse/INF-1240)
Add new param to cs_comment service threads api to allow ordering on endorsed status
=> feat: updated api to allow ordering on endorsed status

Gemfile3, Gemfile3.lock, config.ru, config/unicorn_tcp.rb
Setting datadog instrumentation for forum service.
=> feat: setup datadog instrumentation

.github/workflows/ci.yml, Gemfile, Gemfile.lock, Gemfile3, Gemfile3.lock, spec/spec_helper.rb
Ths change add `ddtrace`, which is used in https://github.com/openedx/cs_comments_service/blob/8626d44a6322a813e8c58140b8b2f3039735709c/config/unicorn_tcp.rb#L15 
Related issue:  
- https://github.com/overhangio/tutor-forum/issues/33
=> bump: add ddtrace in Gemfile

config/unicorn_tcp.rb
Move data dog configurations behind a new flag  To make sure it does not cause any issues with deployments without data dog setup.
https://2u-internal.atlassian.net/browse/INF-1420
=> fix: move data dog config behind flag

.github/workflows/ci.yml, Gemfile, Gemfile.lock, Gemfile3, Gemfile3.lock, config/unicorn_tcp.rb, spec/spec_helper.rb
This PR just to sync `master` with `open-release/redwood.master` since there are only two commits exists between cut date and now no need for backport. 
To be merged before open-release/redwood.2 release
=> Add ruby update to redwood

config/mongoid.yml
This change just fix the name of the variable that is
respoinsbile for:
> The time to wait to establish a connection before timing out,
>  in seconds
ref: https://www.mongodb.com/docs/offline/mongoid-7.5.tar.gz
=> fix: set the correct config name `connect_timout` mongoid
